---
title: "Using dynamic branching to paralellize over raster tiles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using dynamic branching to paralellize over raster tiles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(geotargets)
library(targets)
library(terra)
library(dplyr)
```

## Parallelizing over tiles

Some raster operations can be 

## Tile helpers

## Blocksize, what is it and why use it

## Example targets pipeline

Here's an example `targets` pipeline using `tar_terra_tiles()` demonstrating the improved efficiency from using tiles that are multiples of the native file blocksize over using the same number of arbitrary shaped tiles.

```{r}
tar_dir({
    tar_script({
        ## contents of _targets.R ##############################################
        library(targets)
        library(geotargets)
        library(terra)
        tar_option_set(controller = crew::crew_controller_local(workers = 2))
        list(
            tar_target(
                raster_file,
                system.file("ex/elev.tif", package="terra"),
                format = "file"
            ),
            tar_terra_rast(
                r,
                rast(raster_file)
            ),
            tar_terra_rast(
                r_big,
                disagg(r, fact = 3)
            ),
            tar_terra_tiles(
                tiles_blocksize,
                raster = r_big,
                tile_fun = tile_blocksize
            ),
            tar_terra_tiles(
                tiles_n,
                raster = r_big,
                tile_fun = \(x) tile_n(r_big, n = 72)
            ),
            tar_terra_rast(
                sqrt_blocksize,
                sqrt(tiles_blocksize),
                pattern = map(tiles_blocksize)
            ),
            tar_terra_rast(
                sqrt_n,
                sqrt(tiles_n),
                pattern = map(tiles_n)
            )
        )
    })
    ############################################################################
    
    tar_make()
    tar_meta() |>
        select(name, seconds) |> 
        filter(name %in% c("sqrt_blocksize", "bytes", "sqrt_n"))
}) 
```

